language: shell
# cache:
#   directories:
#   - "$HOME/google-cloud-sdk/"
#   - "google_containers_mirror_completed_list"
services:
- docker
install: docker images 
env:
  global: 
  - repo=registry.cn-hangzhou.aliyuncs.com/nfyxhan/gcr
  - registry=registry.cn-hangzhou.aliyuncs.com
script:
- bash sync_image.sh
